name: Build Docker Image

on:
  push:
    branches:
      - master
      - 'dev/**'
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      docker_registry: ghcr.io
      docker_image: nilium/riak
      ref: ${{ github.ref }}
      commit_sha: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Select Tag
        run: |
          ref="${ref#refs/heads/}"
          case "$ref" in
          master) tag=latest;;
          actions) tag=test;;
          release/*) tag="${ref#release/}";;
          dev/*) tag="${ref#dev/}-latest";;
          *) exit 1;;
          esac
          echo "${docker_registry:+${docker_registry}/}${docker_image}:${tag}" | tee .docker-image
          echo "${docker_registry:+${docker_registry}/}${docker_image}:git-${commit_sha}" | tee .docker-image-sha

      - name: Build Image
        run: |
          image="$(cat .docker-image)"
          docker build \
            --label dev.nil.git.sha1="${commit_sha}" \
            --label dev.nil.git.ref="${ref}" \
            --tag "${image}" \
            .
          image_sha="$(cat .docker-image-sha)"
          docker tag "${image}" "${image_sha}"

      - name: Push Image
        if: github.event_name == 'push'
        env:
          docker_password: ${{ secrets.GITHUB_TOKEN }}
        run: |
          image="$(cat .docker-image)"
          image_sha="$(cat .docker-image-sha)"
          docker login ${docker_registry:+"${docker_registry}"} --username "$GITHUB_ACTOR" --password-stdin <<<"$docker_password"
          docker push "${image}"
          docker push "${image_sha}"
